/** Concept registry ids whose published docs page lives under `/docs/concepts`. */
export const PUBLISHED_CONCEPT_SECTION_REGISTRY_IDS = new Set<string>([
  "concept.transformer-architecture",
  "concept.positional-encodings",
]);

/** Registry ids for docs pages with `status: published` in frontmatter. */
export const PUBLISHED_DOCS_REGISTRY_IDS = new Set<string>([
  "module.attention",
  "module.grouped-query-attention",
  "concept.token",
  "concept.embedding",
  "concept.tensor",
  "concept.vector",
  "concept.hidden-size",
  "concept.logit",
  "concept.softmax",
  "concept.entropy",
  "concept.temperature",
  "concept.parameter",
  "concept.activation",
  "concept.computational-graph",
  "concept.gradient",
  "concept.backpropagation",
  "concept.loss-function",
  "concept.optimizer-state",
  "concept.model",
  "concept.architecture",
  "concept.module",
  "concept.component",
  "concept.modality",
  "concept.foundation-model",
  "concept.generative-model",
  "concept.discriminative-model",
  "concept.representation",
  "concept.patch",
  "concept.latent",
  "concept.latent-space",
  "concept.encoder",
  "concept.decoder",
  "concept.encoder-decoder",
  "concept.autoregressive-generation",
  "concept.denoising-generation",
  "concept.conditioning",
  "concept.alignment",
  "concept.model-capacity",
  "concept.overfitting",
  "concept.generalization",
  "concept.perplexity",
  "concept.scaling-law",
  "concept.emergent-behavior",
  "concept.transformer-architecture",
  "concept.feed-forward-network",
  "concept.mixture-of-experts",
  "concept.normalization",
  "concept.layer-norm",
  "concept.rmsnorm",
  "concept.residual-connection",
  "concept.positional-encodings",
  "concept.rope",
]);

export type PublishedDocsRegistryIds = ReadonlySet<string>;
