/** Registry ids for docs pages with `status: published` in frontmatter. */
export const PUBLISHED_DOCS_REGISTRY_IDS = new Set<string>([
  "module.grouped-query-attention",
  "concept.token",
  "concept.model",
  "concept.architecture",
  "concept.module",
  "concept.component",
  "concept.modality",
  "concept.foundation-model",
  "concept.generative-model",
  "concept.discriminative-model",
  "concept.representation",
  "concept.patch",
  "concept.latent",
  "concept.latent-space",
  "concept.encoder",
  "concept.decoder",
  "concept.encoder-decoder",
  "concept.autoregressive-generation",
  "concept.denoising-generation",
  "concept.conditioning",
  "concept.alignment",
  "concept.model-capacity",
  "concept.overfitting",
  "concept.generalization",
  "concept.perplexity",
  "concept.scaling-law",
  "concept.emergent-behavior",
]);

export type PublishedDocsRegistryIds = ReadonlySet<string>;
