import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { deriveShippedLocalizedDocsManifest } from "@/lib/content/shipped-localized-docs.server";

const outputPath = path.join(
  process.cwd(),
  "src/generated/shipped-localized-docs.ts",
);
const manifest = deriveShippedLocalizedDocsManifest();

const fileContents = `// Generated by scripts/generate-shipped-localized-docs.ts
export const SHIPPED_LOCALIZED_DOCS = ${JSON.stringify(manifest, null, 2)} as const;
`;

mkdirSync(path.dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContents, "utf8");

console.log(`Wrote shipped localized docs manifest to ${outputPath}`);
