import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { loadPublishedDocsPagesSync } from "../src/lib/content/pages";
import {
  buildPublishedDocsIndex,
  deriveModuleBackedConceptRegistryIds,
  derivePublishedConceptSectionRegistryIds,
  derivePublishedDocsRegistryIds,
} from "../src/lib/content/published-docs-registry-source";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, "..");
const outputPath = join(
  repoRoot,
  "src/lib/content/published-docs-registry-manifest.ts",
);

const index = buildPublishedDocsIndex(loadPublishedDocsPagesSync("en"));
const entries = index.entries.map(({ pageDir: _pageDir, ...entry }) => entry);

const fileContents = `// Generated by scripts/generate-published-docs-registry.ts
// Do not edit by hand.

export const GENERATED_PUBLISHED_DOCS_ENTRIES = ${JSON.stringify(
  entries,
  null,
  2,
)} as const;

export const GENERATED_PUBLISHED_DOCS_REGISTRY_IDS = ${JSON.stringify(
  derivePublishedDocsRegistryIds(index),
  null,
  2,
)} as const;

export const GENERATED_PUBLISHED_CONCEPT_SECTION_REGISTRY_IDS = ${JSON.stringify(
  derivePublishedConceptSectionRegistryIds(index),
  null,
  2,
)} as const;

export const GENERATED_MODULE_BACKED_CONCEPT_REGISTRY_IDS = ${JSON.stringify(
  deriveModuleBackedConceptRegistryIds(index),
  null,
  2,
)} as const;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, fileContents);

const formatResult = spawnSync(
  "bunx",
  ["biome", "format", "--write", outputPath],
  {
    cwd: repoRoot,
    encoding: "utf8",
  },
);

if (formatResult.status !== 0) {
  throw new Error(
    `Failed to format ${relative(repoRoot, outputPath)}: ${
      formatResult.stderr || formatResult.stdout
    }`,
  );
}

console.log(`wrote ${relative(repoRoot, outputPath)}`);
